/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dacs1.v2;

import java.awt.event.ActionEvent;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class MainForm extends javax.swing.JFrame {

    private String currentUsername;
    private String currentUserRole;
    private File selectedFile;
    private Timer refreshTimer;

    public MainForm(String username, String role) {
        this.currentUsername = username;
        this.currentUserRole = role;
        initComponents();
        lblUsername.setText("Người dùng: " + username);
        refreshFileList();
        refreshTimer = new Timer(5000, e -> refreshFileList());
        refreshTimer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelectFile = new javax.swing.JButton();
        txtReceiver = new javax.swing.JTextField();
        btnSendFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFiles = new javax.swing.JTable();
        btnDownload = new javax.swing.JButton();
        txtSelectedFile = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnSelectFile.setText("Chọn File");
        btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFileActionPerformed(evt);
            }
        });

        txtReceiver.setText("Nhập tên người nhận");
        txtReceiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReceiverActionPerformed(evt);
            }
        });

        btnSendFile.setText("Gửi File");
        btnSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendFileActionPerformed(evt);
            }
        });

        tblFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên file", "Người gửi", "Người nhận", "Size", "Thời gian"
            }
        ));
        jScrollPane1.setViewportView(tblFiles);
        if (tblFiles.getColumnModel().getColumnCount() > 0) {
            tblFiles.getColumnModel().getColumn(0).setPreferredWidth(140);
            tblFiles.getColumnModel().getColumn(1).setPreferredWidth(130);
            tblFiles.getColumnModel().getColumn(2).setPreferredWidth(140);
            tblFiles.getColumnModel().getColumn(4).setPreferredWidth(260);
        }

        btnDownload.setText("Tải File");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        txtSelectedFile.setText("Tên File");

        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblUsername.setBackground(new java.awt.Color(102, 255, 102));
        lblUsername.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("APP QUẢN LÍ FILE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSelectedFile, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSelectFile, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(btnSendFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSendFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSelectedFile, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReceiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReceiverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReceiverActionPerformed

    private void btnSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFileActionPerformed
    JFileChooser fc = new JFileChooser();
    if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        selectedFile = fc.getSelectedFile();
        txtSelectedFile.setText(selectedFile.getName());
    }
    }//GEN-LAST:event_btnSelectFileActionPerformed

    private void btnSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendFileActionPerformed
    String receiver = txtReceiver.getText().trim();
        if (selectedFile == null || receiver.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn file và nhập người nhận");
            return;
        }

        btnSendFile.setEnabled(false); // Disable button to prevent multiple clicks
        SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() {
                System.out.println("Sending file: " + selectedFile.getName() + " to " + receiver);
                return ClientSocketManager.sendFile(selectedFile, currentUsername, receiver);
            }

            @Override
            protected void done() {
                try {
                    String response = get();
                    if ("FILE_RECEIVED".equals(response)) {
                        JOptionPane.showMessageDialog(MainForm.this, "Gửi file thành công!");
                        refreshFileList();
                    } else {
                        JOptionPane.showMessageDialog(MainForm.this, "Gửi file thất bại: " + response);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(MainForm.this, "Lỗi khi gửi file: " + e.getMessage());
                    e.printStackTrace();
                } finally {
                    btnSendFile.setEnabled(true); // Re-enable button
                }
            }
        };
        worker.execute();
    }//GEN-LAST:event_btnSendFileActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
    int row = tblFiles.getSelectedRow();
        if (row >= 0) {
            String filename = (String) tblFiles.getValueAt(row, 0);
            String sender = (String) tblFiles.getValueAt(row, 1);
            ClientSocketManager.downloadFile(filename, sender, currentUsername);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một file để tải về");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    refreshFileList();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void refreshFileList() {
        try {
            System.out.println("Làm mới danh sách file cho: " + currentUsername);
            List<FileRecord> records = ClientSocketManager.getFilesForUser(currentUsername, currentUserRole);
            System.out.println("Nhận " + records.size() + " bản ghi file");
            for (FileRecord r : records) {
                System.out.println("File: " + r.filename + ", Gửi: " + r.sender + ", Nhận: " + r.receiver);
            }
            DefaultTableModel model = (DefaultTableModel) tblFiles.getModel();
            model.setRowCount(0);
            for (FileRecord r : records) {
                model.addRow(new Object[]{r.filename, r.sender, r.receiver, r.size, r.uploadTime});
            }
            tblFiles.repaint();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải danh sách file: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm("guest", "USER").setVisible(true); // 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JButton btnSendFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblFiles;
    private javax.swing.JTextField txtReceiver;
    private javax.swing.JTextField txtSelectedFile;
    // End of variables declaration//GEN-END:variables
}
